[phases.setup]
# This installs the missing Linux libraries for OpenCV
nixPkgs = ["python313", "ffmpeg", "libsm", "libice", "libxext", "libxrender", "libglvnd", "xorg.libxcb", "xorg.libX11"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[start]
# Make sure main1:app matches your filename
cmd = "uvicorn main1:app --host 0.0.0.0 --port $PORT"